model_family: llama2-7b

LoRA:
  r: 0
  alpha: 32
  dropout: 0.05

data_path: /home/cuisen/users/urkax/LLM_data/TOFU/dataset
split: full
batch_size: 16
gradient_accumulation_steps: 1
num_epochs: 5
lr: 1e-5
save_dir: ft_epoch${num_epochs}_lr${lr}_${model_family}_${split}_wd${weight_decay}

weight_decay: 0.01
seed: 42